packages/topotal-ui/src/components/Card/index.stories.tsx
packages/topotal-ui/src/components/Card/index.tsx
packages/topotal-ui/src/components/Card/styles.ts

feat(topotal-ui): Add Card component

---

packages/topotal-ui/src/components/TextInput/hooks.ts
packages/topotal-ui/src/components/TextInput/index.stories.tsx
packages/topotal-ui/src/components/TextInput/index.tsx

fix: patch TextInput bug

---

packages/topotal-ui/src/components/Button/index.stories.tsx
packages/topotal-ui/src/components/Button/types.ts
packages/topotal-ui/src/components/Button/utils.ts

feat: Add positive color to Button

---

packages/topotal-ui/src/components/Card/index.stories.tsx
packages/topotal-ui/src/components/Card/index.tsx

fix: Add gap to header and footer in Card

---

packages/topotal-ui/src/components/ScreenFrame/index.stories.tsx
packages/topotal-ui/src/components/ScreenFrame/index.tsx
packages/topotal-ui/src/components/ScreenFrame/styles.ts

fix: Patch maxWidth as ScreenFrame

---

packages/topotal-ui/src/components/Button/index.tsx

fix: patch Button props bug

---

packages/topotal-ui/src/components/Button/index.tsx
packages/topotal-ui/src/components/Button/styles.ts
packages/topotal-ui/src/components/Button/utils.ts

fix: patch Button style

---

packages/topotal-ui/.eslintrc.json

fix(eslint): Patch indent rule

---

packages/topotal-ui/CHANGELOG.md
packages/topotal-ui/package.json
packages/topotal-ui/src/components/Dropdown/index.tsx
packages/topotal-ui/src/components/ScrollView/index.tsx
packages/topotal-ui/src/theme/index.ts

fix: patch Dropdown bug

---

packages/topotal-ui/src/components/MdRenderer/index.stories.tsx
packages/topotal-ui/src/components/MdRenderer/utils.ts

テキストの先頭にスペースが入っていた場合に削除されてしまうバグを修正

fix: Add head space to MdRenderer text

---

packages/topotal-ui/package.json
packages/topotal-ui/src/components/MdRenderer/index.stories.tsx
packages/topotal-ui/src/components/MdRenderer/utils.ts
yarn.lock

#53 の解消のためにDOMParserを使うのをやめ、samitize-htmlを使用するように変更

feat: Add sanitize-html

---

packages/topotal-ui/src/components/TextInput/index.stories.tsx
packages/topotal-ui/src/components/TextInput/index.tsx
packages/topotal-ui/src/components/TextInput/styles.ts
packages/topotal-ui/src/components/TextInput/utils.ts

feat(topotal-ui): Add size prop to TextInput

---

packages/topotal-ui/package.json
yarn.lock

chore(topotal-ui): Update marked

---

packages/topotal-ui/src/components/MdRenderer/components/Paragraph/index.tsx
packages/topotal-ui/src/components/MdRenderer/components/Switcher/index.tsx
packages/topotal-ui/src/components/MdRenderer/index.stories.tsx

リスト内でのリンクの対応
（やっつけコードなのでかならずどこかでリファクタを行う）

fix(topotal-ui): Support link in list item

---

packages/topotal-ui/src/components/MdRenderer/components/CodeSpan/index.tsx
packages/topotal-ui/src/components/MdRenderer/components/Paragraph/index.tsx
packages/topotal-ui/src/components/MdRenderer/index.stories.tsx

feat: Add CodeSpan to MdRenderer

---

packages/topotal-ui/src/components/BaseStack/index.tsx
packages/topotal-ui/src/components/Button/index.tsx
packages/topotal-ui/src/components/Card/index.tsx
packages/topotal-ui/src/components/Dropdown/index.tsx
packages/topotal-ui/src/components/FixedRatioView/index.tsx
packages/topotal-ui/src/components/GridList/index.tsx
packages/topotal-ui/src/components/Icon/index.tsx
packages/topotal-ui/src/components/InputFrame/index.tsx
packages/topotal-ui/src/components/List/index.tsx
packages/topotal-ui/src/components/MdRenderer/index.tsx
packages/topotal-ui/src/components/Picker/index.tsx
packages/topotal-ui/src/components/Separater/index.tsx
packages/topotal-ui/src/components/Skelton/index.tsx
packages/topotal-ui/src/components/Spacer/index.tsx
packages/topotal-ui/src/components/SyntaxHighlighter/index.tsx
packages/topotal-ui/src/components/TagInput/index.tsx
packages/topotal-ui/src/components/Text/index.tsx
packages/topotal-ui/src/components/TextArea/index.tsx
packages/topotal-ui/src/components/TextInput/index.tsx
packages/topotal-ui/src/components/ThemeProvider/index.tsx
packages/topotal-ui/src/components/UserIcon/index.tsx

https://github.com/topotal/js-sdk/blob/199c9c7c3f9f2108be7711210994a4c4436006a7/packages/topotal-ui/src/components/index.ts を元に testId 追加しました！

Add testId to all components exported to outside

---

packages/topotal-ui/src/components/Picker/index.stories.tsx
packages/topotal-ui/src/components/Picker/index.tsx
packages/topotal-ui/src/components/Picker/styles.ts

feat: Add startIconName prop to Picker

---

packages/topotal-ui/.storybook/main.js
packages/topotal-ui/package.json

fix: storybook settings

---

packages/topotal-ui/package.json
packages/topotal-ui/src/components/MdRenderer/components/Blockquote/index.tsx
packages/topotal-ui/src/components/MdRenderer/components/Heading/index.tsx
packages/topotal-ui/src/components/MdRenderer/components/Link/index.tsx
packages/topotal-ui/src/components/MdRenderer/components/Paragraph/index.tsx
packages/topotal-ui/src/components/MdRenderer/components/Strong/index.tsx
packages/topotal-ui/src/components/MdRenderer/components/Switcher/index.tsx
packages/topotal-ui/src/components/MdRenderer/index.stories.tsx
packages/topotal-ui/src/components/MdRenderer/index.tsx
packages/topotal-ui/src/components/MdRenderer/utils.ts
yarn.lock

引用文の記法を使っても何も表示されてなかったので追加。併せて~無駄にサニタイズを二重行っていたところを修正~ サニタイズを末尾で行っていたのを token の変換時に行うように修正。
ref: https://github.com/topotal/waroom/issues/905

feat: Add Blockquote

---

packages/topotal-ui/src/components/Tag/index.stories.tsx
packages/topotal-ui/src/components/Tag/index.tsx
packages/topotal-ui/src/components/Tag/styles.ts

fix: Change onPressRemove to optional in tag props

---

packages/topotal-ui/src/components/Card/index.stories.tsx
packages/topotal-ui/src/components/Card/styles.ts

Card の中身が position: absolute の時にカードをはみ出すことができなくなっていたので修正

fix: Card style

---

packages/topotal-ui/src/components/InputField/index.stories.tsx
packages/topotal-ui/src/components/InputField/index.tsx

InputField の description のフォントサイズを12に変更

fix: InputField description

---

packages/topotal-ui/src/components/Dropdown/index.stories.tsx
packages/topotal-ui/src/components/Dropdown/index.tsx
packages/topotal-ui/src/components/Dropdown/styles.ts

feat: Add right-bottom align to Dropdown

---

packages/topotal-ui/src/components/TextArea/index.stories.tsx
packages/topotal-ui/src/components/TextArea/index.tsx
packages/topotal-ui/src/components/TextArea/styles.ts

completionView に View を渡すとカーソル位置に View が表示されるように修正

feat: TextArea completion

---

packages/topotal-ui/src/components/TextArea/index.stories.tsx
packages/topotal-ui/src/components/TextArea/index.tsx

TextArea への forwardRef の追加とvalue の取り回しを修正

fix: Add forwardRef to textarea

---

packages/topotal-ui/src/components/BaseStack/index.tsx
packages/topotal-ui/src/components/HStack/index.tsx
packages/topotal-ui/src/components/Text/index.tsx
packages/topotal-ui/src/components/VStack/index.tsx

https://github.com/topotal/waroom-frontend/issues/1295
next/linkのコンポーネント：`Link`の子要素になっている`topotal-ui`のコンポーネントを洗い出し、forwardRefを使いrefを受けられるように修正する。
##調査内容について
|対象コード|修正要否|備考|
|---|---|---|
|./src//screens/TeamsScreen/components/TeamsListItem/index.tsx	|不要|topotal-uiを使っていない/子要素は文字列|
|./src//screens/RunbooksScreen/components/DirectoryRow/index.tsx	|不要|topotal-uiを使っていない/子要素は文字列|
|./src//screens/RunbooksScreen/components/FileRow/index.tsx	|不要|topotal-uiを使っていない/子要素は文字列|
|./src//screens/RunbooksScreen/components/BackRow/index.tsx	|不要|topotal-uiを使っていない/子要素は文字列|
|./src//screens/RunbookRulesScreen/components/RunbookRulesListItem/index.tsx	|不要|topotal-uiを使っていない/子要素は文字列|
|./src//screens/IncidentsScreen/components/IncidentsListItem/index.tsx	|不要|topotal-uiを使っていない/子要素は文字列| …

Add forwardRef to Component

---

packages/topotal-ui/src/components/Separater/styles.ts

https://github.com/topotal/js-sdk/issues/330
separatorの文字色を変更しました！

Fix separator color style

---

.github/workflows/deploy-docs.yml

Waroom の Staging にデプロイ情報を送ってみる

chore: Add waroom deployment step

---

packages/topotal-ui/package.json

- 前回バージョンを上げたことによりビルドは通っていたのですが、storyが立ち上がらなくなっていることに気づけませんでした。。。
- react-domのバージョンも上げる必要があったので、こちらも上げました。
- 前回上げていたものを戻してしまったみたいでした。
前回のPR:https://github.com/topotal/js-sdk/pull/388/files

Fix react-native-web version

---

packages/topotal-ui/src/components/ToggleSwitch/index.stories.tsx
packages/topotal-ui/src/components/ToggleSwitch/index.tsx
packages/topotal-ui/src/components/ToggleSwitch/utils.ts

https://github.com/topotal/js-sdk/issues/389
- ToggleSwitchコンポーネントのサイズを実装しました。
- M, Sを実装していますが、Sは仮になります

Toggle switch size

---

packages/topotal-ui/package.json
packages/topotal-ui/src/components/Button/index.stories.tsx
packages/topotal-ui/src/components/Button/index.tsx
yarn.lock

loading のステータスが変わった時になぜか onPress が onPressIn, onPressOut の両方で動いてしまっていたので onPressOut で明示的に動かすように暫定修正

fix: Button onPress bug

---

.github/workflows/deploy-docs.yml

Use https://github.com/topotal/waroom-deployment-tracking-action instead of curl command.
@sawa-zen Could you review it?

Use topotal/waroom-deployment-tracking-action@v1

---

packages/topotal-ui/package.json
packages/topotal-ui/src/components/SelectTagInput/hooks.ts
packages/topotal-ui/src/components/SelectTagInput/index.stories.tsx
packages/topotal-ui/src/components/SyntaxHighlighter/components/Child/index.tsx
packages/topotal-ui/src/components/SyntaxHighlighter/components/ElementChild/index.tsx
packages/topotal-ui/src/components/SyntaxHighlighter/components/Renderer/index.tsx
packages/topotal-ui/src/components/SyntaxHighlighter/types.ts
yarn.lock

SelectTagInput でフィルターをかけた状態で選択肢をクリックできないバグを修正しました。
ref: https://github.com/topotal/waroom/issues/1440

fix: SelectTagInput

---

packages/topotal-ui/src/components/ToggleSwitch/index.stories.tsx
packages/topotal-ui/src/components/ToggleSwitch/index.tsx

Toggle Switch に disabled の attribute を追加しました。

feat: Add disabled attribute to toggle switch

---

packages/topotal-ui/src/components/Picker/index.tsx
packages/topotal-ui/src/components/Picker/styles.ts

fix: Picker style

---

packages/topotal-ui/src/components/TextArea/index.stories.tsx
packages/topotal-ui/src/components/TextArea/index.tsx

onCmdEnterPress から value を受け取れるように修正

fix: TextArea onCmdEnterPress

---

packages/topotal-ui/package.json
yarn.lock

Revert "chore(deps-dev): bump @storybook/cli from 7.6.10 to 8.5.3"
